name: SBOM Scanner product documentation preview - publish to GitHub Pages with Lunr Search Extension

on:
  # Runs whenever changes are pushed to the main branch.
  push:
    branches:
      - main

  # Allows manual execution from the GitHub Actions tab.
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Configure GitHub Pages
        uses: actions/configure-pages@b8130d9ab958b325bbde9786d62f2c97a9885a0e # v3.0.7

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Install Antora and Lunr search extension
        run: make environment

      - name: Build SBOM Scanner documentation site
        run: make product-remote 

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: build/site

      - name: Publish static site to gh-pages branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          mv build/site ../site-temp

          git checkout --orphan gh-pages
          git rm -rf .

          rm -rf node_modules tmp

          mv ../site-temp/* .

          git add .
          git commit -m "Deploy documentation site"
          git push --force origin gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
